# Generated by Django 3.1.1 on 2020-09-06 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Monto')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Pregunta')),
                ('option_a', models.CharField(max_length=250, verbose_name='Opción A')),
                ('option_b', models.CharField(max_length=250, verbose_name='Opción B')),
                ('option_c', models.CharField(max_length=250, verbose_name='Opción C')),
                ('option_d', models.CharField(max_length=250, verbose_name='Opción D')),
                ('correct_answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=5, verbose_name='Respuesta correcta')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Tiempo')),
                ('score', models.IntegerField(verbose_name='Puntuación')),
                ('call_friend', models.BooleanField(default=False, verbose_name='LLamar a un amigo')),
                ('audience', models.BooleanField(default=False, verbose_name='Consultar a la audiencia')),
                ('fifty_fifty', models.BooleanField(default=False, verbose_name='50-50')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
